### PR TITLE
Fix timestamp to have correct month and use UTC timezone

### PR DESCRIPTION
**Pull request by gs640**
//cc @aldryd @rk-yen

### CODE REVIEW

**Comment by rk-yen** [comment]
JIRA ticket?

;)

:+1:

**Comment by aldryd** [comment]
I'm surprised there isn't already a Pull Request in the main repo for that bug.

:+1:

**Comment by rk-yen** [comment]
Ref: https://github.com/mattconnolly/ZipArchive/issues/50

**Comment by rk-yen** [comment]
One suggestion would be to split the actual bug fix and the UTC time change into separate commits.

**Comment by rk-yen** [comment]
And then, the podspec change in it's own commit.

**Comment by gs640** [comment]
Updated

**Comment by rk-yen** [comment]
:+1:

**Pull request merged**
